### PR TITLE
💾 Added maximum lengths to combo titles and notes

### PR DESCRIPTION
**Pull request by sleeping-dev**
I saw your list in the discord and to try out this 'contributing' thing I figured I'd add a max length to combo titles and notes. I chose the values after testing it out a bit, I think 128 chars for the Title and 512 chars for Notes should be enough to get all the information one would need across.

### CODE REVIEW

**Comment by sleeping-dev** [comment]
Thanks for reviewing. I think I'll leave it as is, since EF Core generated it that way, just to be sure, but good looking out!

**Comment by Breadkenty** [comment]
This is great, I am actually thinking about removing the titles since I've got a few feedbacks bout combos not needing titles at all. But something for the future. Is it necessary to set error handling on the backend? Usually I have error messages sent back to me when there is a bad request which changes the `errorMessage` state in react. 

Aside from that, I'm gonna go ahead and accept this once I hear back from y'all. Thanks and great job @sleeping-dev !

**Comment by skittlz444** [comment]
@Breadkenty Code passed from me. You can check the status of reviewer's in the top right of the PR under the "Reviewers" section.

**Comment by sleeping-dev** [comment]
@Breadkenty Can you elaborate on what you mean by error handling? As long as we keep the constraints on the frontend inputs equal to the db constraints we should be able to avoid any database exceptions. 

And if we go through with #9 we can handle database exceptions on the implementation of the database itself and just return null or whatever to the controllers when something goes wrong. From what I've seen the controllers already correctly return error messages when the database returns null so there shouldn't be any big necessary changes.

**Comment by skittlz444** [comment]
@sleeping-dev I'd recommend against "silently" handling the errors, best practice is to throw and catch exceptions at various points (usually custom exceptions as things get more complex). But for now, [no need to re-invent the wheel](https://stackoverflow.com/a/38935583).

**Comment by sleeping-dev** [comment]
Fair enough, that's probably the best solution.

**Comment by Breadkenty** [comment]
So to elaborate on the error handling point, there are a couple of ways of how bad inputs are handled.

The input tag here: https://github.com/Breadkenty/Smash_Combos/blob/37dcf9d0fce71342b9c4412e59486511f21ad159/ClientApp/src/pages/SubmitCombo.jsx#L415

prevents this answer to be null. However, this does not stop some clever person to make a POST request using some API tool to submit a combo without a title.

So to deal with this, I have some restriction on the `Combo` model here: https://github.com/Breadkenty/Smash_Combos/blob/37dcf9d0fce71342b9c4412e59486511f21ad159/Models/Combo.cs#L20

This will return a 400 Bad Request and sends the error back in an API response saying "Title is required"

Which is then processed in the UI as a state, setting the `errorMessage` here: https://github.com/Breadkenty/Smash_Combos/blob/37dcf9d0fce71342b9c4412e59486511f21ad159/ClientApp/src/pages/SubmitCombo.jsx#L274-L276

Which is ultimately displayed as an HTML tag here: https://github.com/Breadkenty/Smash_Combos/blob/37dcf9d0fce71342b9c4412e59486511f21ad159/ClientApp/src/pages/SubmitCombo.jsx#L702-L706

This is a way to double-check to make sure that null inputs do not get saved to the database. I think this is what @skittlz444 was getting into, but this is how I have it set up in my code, but it's a little messy.

**Pull request merged**
