### PR TITLE
💾 Miis and the Pokemon were split into separate characters

### PR DESCRIPTION
**Pull request by sleeping-dev**
I split the Pokemon and the Miis up as specified in issue #4 each with their own graphic and went ahead and removed Pokemon Trainer as I don't think they'll be needed anymore now that the 'mons are separate. (The files are still there in case we want to realize @ejbee3 's idea of having the trainer clickable and then the 'mons selectable) I also added the ReleaseOrder to the Character Model, and updated characters.sql to include it for each char. I just gave Echo characters a half-step (eg. Peach = 13, Daisy = 13.5), so they'll always be sorted after their 'original'.

When called from the api, all characters are now sorted by their ReleaseOrder before being shown.

I apologize to @ejbee3 in case this gets accepted, you said you were working on this but I got excited as this is my first project as a contributer and spent the last couple hours on this 😅

### CODE REVIEW

**Comment by Breadkenty** [comment]
@sleeping-dev this looks great, I wanna know a little more about what @skittlz444 is referring to. I usually never touch the migration files that `dotnet ef migrations add ...` creates but I'm assuming you are referring to this change?
```
protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<decimal>(
                name: "ReleaseOrder",
                table: "Characters",
                nullable: false,
                defaultValue: 0m);
        }
```

replacing the 
```
migrationBuilder.AddColumn<decimal>(
                name: "ReleaseOrder",
                table: "Characters",
                nullable: false,
                defaultValue: 0m);
```

to 

```
migrationBuilder.Sql(
                name: "ReleaseOrder",
                table: "Characters",
                nullable: false,
                defaultValue: 0m);
```

When you do migrations like this, you usually have to wipe the database to scratch to add things. But does this prevent you from wiping the database over to make changes to your models?

**Comment by sleeping-dev** [comment]
i believe what they meant was to do something along the lines of this:
```
migrationsBuilder.AddColumn<decimal>(
                name: "ReleaseOrder",
                table: "Characters",
                nullable: false,
                defaultValue: 0m);
migrationBuilder.Sql("<SQL COMMANDS FOR ADDING RELEASE ORDER TO EVERY ENTRY>");
```
so that when applying migrations, one wouldn't have to run characters.sql again manually to have the ReleaseOrder values added. I'm thinking of solving this by just running characters.sql again, since it truncates the table and re-adds every character, so it would look something like this:
```
migrationsBuilder.AddColumn<decimal>(
                name: "ReleaseOrder",
                table: "Characters",
                nullable: false,
                defaultValue: 0m);
migrationBuilder.Sql(File.ReadAllText("characters.sql"));
```
Note: for this to work in prod I believe we'd need to add it to the publish directory like this:
In Smash_Combos.csproj:
`<ItemGroup> <Content Include="characters.sql" CopyToPublishDirectory="PreserveNewest" /></ItemGroup>`

Otherwise it won't be copied when deploying, then migrations can't be applied, etc. etc.

Thoughts on this?

**Comment by sleeping-dev** [comment]
Just realized truncating the Characters table would drop all the combos since they depend on the Characters to be there, that would be bad! 😅 So I wouldn't use characters.sql but rather write a new script called "addReleaseOrder.sql" that simply sets the ReleaseOrder value, and include that in my suggested change above.

**Comment by skittlz444** [comment]
@sleeping-dev is right with what I meant. Since it is a once off, it usually is best to type it out into the migrate up method rather than adding a new file.

**Comment by sleeping-dev** [comment]
Alright, I'll write it up and commit after work 👍

**Comment by sleeping-dev** [comment]
I finished the update statements in the migration and am pretty much ready to commit. But when testing it I noticed that currently when setting up, it is still required to manually run `psql Smash_ComboDatabase --file=Models/characters.sql` as the characters are not added automatically during a migration.

I tested the migration by dropping and recreating the database, and as I forgot to run `psql Smash_ComboDatabase --file=Models/characters.sql` there were no characters for the current migration to update.

We could avoid this by automatically inserting the characters into the database during the AllTables-Migration I think?
That would remove the need to keep a characters.sql file and make the setup for other devs easier.

I don't think there's any problems with that, since I'm only adding Insert statements to an existing migration, right? That shouldn't impact databases that already have this migration applied, since those probably already have the data inserted anyway.

**Comment by sleeping-dev** [comment]
I went ahead and tried it out and it worked, couldn't find any problems! Basically what I changed:

- Changed the Migration name to something more accurate
- Added the data updates to the newest migration as we discussed. Instead of using `migrationBuilder.Sql()` I used `migrationBuilder.UpdateData()`, it looks a bit cleaner than a long string.
- Changed the ReleaseOrder for Yoshi in characters.sql from 5 -> 6, that was a typo from the last commit.
- Added the Character insertions from characters.sql into the Migration "AllTables", that way when setting up an environment for the app to run, there is **no more need** to run `psql Smash_ComboDatabase --file=Models/characters.sql`, as the characters are automatically inserted when running `dotnet ef database update`

`characters.sql` is now obsolete, as its only purpose was to fill the database with characters when setting up an environment, that now happens automatically, should be cleaner 👍 

Thoughts?

**Comment by skittlz444** [comment]
@sleeping-dev Brilliant, I really like the changes to make running the characters sql obsolete. It all looks good, the only thing left to do is to update the contributions readme to reflect the changes of not needing to run characters sql anymore. Good work.

**Comment by Breadkenty** [comment]
Wow @sleeping-dev, I'm still learning what you're doing here but this is awesome great job!

**Comment by sleeping-dev** [comment]
Thanks guys 👍 
Alright, the documentation is updated and I also went ahead and deleted characters.sql while I was at it! I think this should be all, feel free to approve/pull this one.

@Breadkenty if you have any questions feel free to message me!

**Pull request merged**
