### PR TITLE
🦟 Fixed Migrations so that existing databases will have their discrepancies removed during Migrations

### LINKED ISSUE #12: Remove Pokemon Trainer, and Add Individual Miis and PT Pokemon for Databases that were created Pre Release Order

### PR DESCRIPTION
**Pull request by sleeping-dev**
Fixed #12, and fixed a small bug where characters were not sorted by their release order on the main page. Also removed an import of the pokemon trainer image, since we don't need it for the time being.

A few words on why I chose to delete and re-add the entries during the migration because it looks a bit weird:

The MigrationBuilder doesn't provide methods for performing **upserts**, and performing them in postgreSQL requires the use of an [INSERT ON CONFLICT statement](https://www.postgresqltutorial.com/postgresql-upsert/), which basically checks against a provided **unique** column to see if an entry exists or not. The column **needs** to be unique otherwise it doesn't work. The only unique column our Characters table has is the Id, which is generated by the database, so I didn't want to hardcode an Id into the statement and _hope_ that every database that's set up has that exact Id for, e.g. Squirtle. 

There is the possibility to use concurrent operations, as suggested in one of the answers in [this thread](https://stackoverflow.com/questions/4069718/postgres-insert-if-does-not-exist-already#13342031), but apparently that can cause problems so I chose the simpler, safer approach.

### CODE REVIEW

**Comment by skittlz444** [comment]
The issue with deleting those rows is the reliance of combos on characters.
If cascade delete is set up, it will wipe any of the combos for them. It might be a problem for instance if I go onto staging now and add a squirtle combo. It would only affect staging at this point so that's not too bad. 
If cascade delete isn't set up however (I haven't double checked if it has), then the delete statement will fail, causing the migration to fail and further migrations to not run. If there are any pokemon trainer combos in production, this could happen there.
You could use .Sql() with the following if logic to avoid the race condition mentioned in that post
`IF EXISTS (SELECT FROM x WHERE y) THEN
    INSERT... 
END IF;`

I don't have a chance to look at it right now, could you look and let me know if cascade delete is set up correctly? If not you'll have to select and delete all of those that link to PT, and in the same way you'll have to do the same for any sub objects of combo where cascade isn't set up, etc.

Also, be sure to provide a migrate down method. It might seem silly since it'll be re adding "junk data" in pokemon trainer, but if the migration fails, the database should roll back as close as possible to the previous state.

**Comment by sleeping-dev** [comment]
You're completely right, I wrote this in a bit of a rush today and totally forgot about the combos that could already be there, even if its not many at this point, it should still be taken care of.

I'm going to bed now, just checked on my phone quickly and cascading delete seems to be set up on characters and combos. I'll go over it again tomorrow and make the necessary changes.

**Comment by sleeping-dev** [comment]
Working on it now a bit before work, and I can't get your Sql to work, here's what I have:
```
IF NOT EXISTS(SELECT FROM "Characters" WHERE "VariableName" = 'Squirtle') THEN
    INSERT INTO "Characters" ("Name", "VariableName", "YPosition", "ReleaseOrder")
VALUES('Squirtle', 'Squirtle', 0, 33);
END IF;
```
I keep getting syntax errors: `syntax error at or near "IF"`

Any Idea what I'm doing wrong? (You'll have noticed by now, my SQL is not the best, haha)

I also looked over the Models and it seems Cascading Delete was **not** set up for ComboVotes and CommentVotes, so those would stay in the db when the respecting combos and comments were deleted, I'll either add the needed foreign keys in this migration or make another one, whichever's cleaner.

**Comment by sleeping-dev** [comment]
I made the necessary changes and added Cascading Deletes to votes so they're deleted when their respective comment/combo is deleted.

Thanks for bearing with me, and let me know if I missed anything @skittlz444

**Comment by sleeping-dev** [comment]
Changed it so the foreign key migration runs first now.

**Comment by Breadkenty** [comment]
Great work!

**Pull request merged**
